### ISSUE TITLE
Tabs bind:active doesn't work

### ISSUE THREAD

**Issue by Driez** [c0bra/svelma#118]
binding the `active` property should result in a useable reference to the active Tab  in the form a a zero-based  index,
but doesn't work as intended.

_Current Behaviour:_
- The bound variable will not decide the initial open tab.
- It will not change change the active tab if the value of the bound variable changes in the parent component.
- It will not change the value of the bound variable if another tab becomes active.

_Expected Behaviour:_
- the bound Variable should reflect the open Tab at any point in time. 

Is this part of the documentation old and not up to date? 
I see that there is a value property, but based on what I can tell, this doesnt work as a bindable reference to the active tab index either.

**Comment by Driez** [comment]
based on the source code of the component it looks like `active` is now called `value` and its reference is destroyed after the initial setting of activeTab which is not exported....

As far as I can tell base on my understanding of the source code of the component none of these things are implemented, and there is no good way of finding//changing the active tab now. 

Can anyone maybe elaborate the reason for that?

**Comment by ierror** [comment]
@Driez Have you found a solution how to set the active tab? For me always the last tab is active, regardless of `active` or `value`
