### ISSUE TITLE
hardcoded pack 'fa' for icon 

### ISSUE THREAD

**Issue by hillar** [c0bra/svelma#12]
https://github.com/c0bra/svelma/blob/840617cdb4cfc964917d29bd041cd4f7b78faadc/src/components/Icon.svelte#L53

should it be 
```
<i class="{newPack} {newPack}-{icon} {newPack}-{customClass}  {newCustomSize}" />
```

**Comment by c0bra** [comment]
No, as far as I can tell the icon prefix is always `fa-`.

See this link and how it's using the `fab` pack but the icon class is `fa-github`: https://fontawesome.com/icons/github?style=brands

**Comment by hillar** [comment]
OK, i was just misreading 

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

> You need to know two bits of information to reference an icon, 1) its name, **prefixed** with **fa-** 

https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

> Version 4 just had one prefix — fa. Version 5 has four **prefixes** to let us set the style of any icon easily:
