### ISSUE TITLE
Input outer div class is hardcoded 'control'

### ISSUE THREAD

**Issue by hillar** [c0bra/svelma#13]
```
<Input class="is-expanded" type="text" bind:value={path}/>
```

setting **Input** class to _is-expanded_  is passed to **input**, but as outer div is just 'control' it will not be expanded

```
<div class="control svelte-1v5s752">
   <input type="text" class="input is-expanded svelte-1v5s752" >  
</div>
```

https://github.com/c0bra/svelma/blob/840617cdb4cfc964917d29bd041cd4f7b78faadc/src/components/Input.svelte#L116

maybe someting like this ..

```
<div class="control {$$props.class || ''}" class:has-icons-right={hasIconRight} class:is-loading={loading}>
```

**Comment by c0bra** [comment]
@hillar Latest version (0.3.0) should have you covered: https://c0bra.github.io/svelma/components/field
