### ISSUE TITLE
Add ability to dynamically control tabs

### ISSUE THREAD

**Issue by heokhe** [c0bra/svelma#16]
It would be nice if we could separate the tabs and the main content. for example, I want to put the tabs in a fixed-position header:
```svelte
<script>
  let activeTab = 0;
  function handleTabSwitch(event) {
    activeTab = event.detail.index;
  }
</script>
<header class="site-fixed-header">
  <Tabs on:switch={handleTabSwitch}>
    <Tab label="first tab" /> <!-- activeTab = 0 -->
    <Tab label="second tab" /> <!-- activeTab = 1 -->
  </Tabs>
</header>
<main>
  {#if activeTab === 0}
    first tab
  {:else}
    second tab
  {/if}
</main>
```

**Comment by c0bra** [comment]
Sounds good, thanks for the suggestion!

**Comment by jsfenfen** [comment]
Could this be achieved by exporting changeTab in Tabs.svelte? Then one could bind:this={tab_object} and execute tab_object.changeTab(new_tab_index). 
I think functionally that's just adding `export` on line 53 here: https://github.com/c0bra/svelma/blob/master/src/components/Tabs/Tabs.svelte#L53 .
