### ISSUE TITLE
import 'bulma/css/bulma.css' breaks stuff

### ISSUE THREAD

**Issue by boneskull** [c0bra/svelma#20]
Maybe I'm doing something wrong here, but I added the postcss plugin in my `rollup.config.js`, then did:

```html
<script>
import 'bulma/css/bulma.css';
// other stuff
</script>
```

...but apparently the browser wants to load `bulma.css` as a JS module, because I get a `SyntaxError`.

I'm not using SSR, but it appears the example in `docs` does not do what's recommended in the `README.md`.  

As a workaround, I'll just use a `<link>` tag, but would like to understand how to do it this way.

thanks!

**Comment by c0bra** [comment]
Hey @boneskull , sorry for the long delay. I've tried reproducing this issue but haven't been able to.

If you're still having this problem, could you fire up a small repo that reproduces the problem?  As a first step as well, can you paste your rollup.config.js here too?

**Comment by boneskull** [comment]
I will if/when I pick this up again, but not sure how soon.  feel free to close and I can comment again later if I encounter

**Comment by c0bra** [comment]
Roger, thanks.
