### ISSUE TITLE
Error compile with SSR svelte app

### ISSUE THREAD

**Issue by bipboy** [c0bra/svelma#3]
#### Hello, great job! 
When adding components to an SSR svelte application, it constantly returns a compilation error; an error also occurs when using a Sapper.

> Error: <Button> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
    at validate_component (D:\site\public\App.js:80:15)
    at D:\site\public\App.js:874:12
    at Object.$$render (D:\site\public\App.js:98:22)
    at Object.default (D:\site\public\App.js:900:54)
    at D:\site\public\App.js:828:279
    at Object.$$render (D:\site\public\App.js:98:22)
    at Object.default (D:\site\public\App.js:899:43)
    at D:\site\public\App.js:782:45
    at Object.$$render (D:\site\public\App.js:98:22)
    at D:\site\public\App.js:893:41

It's a rep with the SSR app - https://github.com/Bipboy/svelte-test-ssr

**Comment by c0bra** [comment]
@Bipboy yea you'll need to import the `.svelte` files directly so that your app can compile them, rather than importing the compiled module.

i.e.:

```js
import Button from 'svelma/src/components/Button.svelte'
```

instead of

```js
import { Button } from 'svelma'
```
