### ISSUE TITLE
Support req

### ISSUE THREAD

**Issue by mihaimiculescu** [c0bra/svelma#34]
From the [Dialogs doc](https://c0bra.github.io/svelma/components/dialog):
if I want to use Dialogs I need to `import { Button, Dialog } from 'svelma'`
But I need to use SSR,
from the [npm page](https://www.npmjs.com/package/svelma):

> If you are doing server-side rendering with Sapper, you'll need to import the .svelte files directly so that your app can compile them, rather than importing from the compiled module.

So how should my import line read in order to be able to use Dialog the SSR way?

**Comment by rohfle** [comment]
Either of these ways should work

```javascript
import { Button } from 'svelma/src/index.js';
import Button from 'svelma/src/components/Button.svelte';
```

Also see pull request https://github.com/c0bra/svelma/pull/31 which should allow you to just import components directly when its merged

**Comment by mihaimiculescu** [comment]
Thanks for the reply.
The Button line works OK. I already had tried it.
The problem is with the Dialog line.
I tried to replace
```
import { Button, Dialog } from 'svelma';
```
with
```
import Button from 'svelma/src/components/Button.svelte';
import Dialog from 'svelma/src/components/Dialog';
``` 
but the `Dialog` line is problematic. Even if I put 
```
import Dialog from 'svelma/src/components/Dialog/Dialog.svelte';
```
I still get errors.

**Comment by rohfle** [comment]
```javascript
import Dialog from 'svelma/src/components/Dialog';
```
and the demo code from the docs works for me on Svelma 0.3.0... I'm not using Sapper though...

What do the errors say?

**Comment by mihaimiculescu** [comment]
Actually it was a doc glitch ...
The demo code from [https://c0bra.github.io/svelma/components/dialog](https://c0bra.github.io/svelma/components/dialog) **- first example** uses **Toast** too:
```<script>
  import { Button, Dialog } from 'svelma'
```
...
```
const thenHandler = result =>Toast.create(`You ${result ? 'confirmed' : 'canceled'}`)
```
etc
So, the import line for the first example should read
`import { Button, Dialog, Toast } from 'svelma'`
Otherwise, it generates errors.
Silly me - I could have noticed beforehand ... sry

Could you please fix the doc?

**Comment by mihaimiculescu** [comment]
Actually, still with errors:
```
[!] (plugin svelte) ParseError: Identifier is expected
node_modules/svelma/src/components/Dialog/Dialog.svelte
159: 
160:  .dialog {
161:    .modal-card {
        ^
162:      max-width: 460px;
163:      width: auto;
ParseError: Identifier is expected
    at error (/sveltedev/node_modules/svelte/src/compiler/utils/error.ts:25:16)
    at Parser$2.error (/sveltedev/node_modules/svelte/src/compiler/parse/index.ts:93:3)
    at Object.read_style [as read] (/sveltedev/node_modules/svelte/src/compiler/parse/read/style.ts:20:11)
    at tag (/sveltedev/node_modules/svelte/src/compiler/parse/state/tag.ts:192:27)
    at new Parser$2 (/sveltedev/node_modules/svelte/src/compiler/parse/index.ts:45:12)
    at parse (/sveltedev/node_modules/svelte/src/compiler/parse/index.ts:208:17)
    at compile (/sveltedev/node_modules/svelte/src/compiler/compile/index.ts:68:14)
    at /sveltedev/node_modules/rollup-plugin-svelte/index.js:252:22

```

**Comment by c0bra** [comment]
Done, thanks for finding this!
