### ISSUE TITLE
Sapper version in docs needs to be updated to v0.27.4

### ISSUE THREAD

**Issue by shivchawla** [c0bra/svelma#4]
I tried running the development steps and it threw an error. Package.json in the /docs refer to version of sapper that refers to svelte/store.mjs which is [not valid](https://github.com/sveltejs/svelte/issues/3048). 

I modified it to v0.27.4 and it worked. 

Thanks!

**Comment by c0bra** [comment]
@shivchawla Gotcha! I will update; thanks.

**Comment by c0bra** [comment]
Updated
