### ISSUE TITLE
Are there plans to implement date and time pickers? 

### ISSUE THREAD

**Issue by acim** [c0bra/svelma#41]
Or they are intentionally left?

**Comment by c0bra** [comment]
@acim this library is very much a work in progress, so a lot is not yet done that hasn't _intentionally_ left undone.

That being said, date/time pickers are a special case. They are very, very complicated. Enough that they often stand on their own. I'm not opposed to bringing them into this codebase, but they would create enough of a support requirement that it might be more harmful than good over the long term.

My suggestion for the time being would be to look at vanilla pickers like https://flatpickr.js.org/

**Comment by acim** [comment]
Thank you for the explanation. I would help, but I am not that good in Svelte yet 😊
