### ISSUE TITLE
on:change and on:input issues with Input.svelte

### ISSUE THREAD

**Issue by mihaimiculescu** [c0bra/svelma#48]
Trying to use [Input.svelte](https://github.com/c0bra/svelma/blob/master/src/components/Input.svelte) in a component, like so:
In the script area:
`  import Field from 'svelma/src/components/Field.svelte'`
`  import Input from 'svelma/src/components/Input.svelte'`
In the html area:
`<Input type="text" bind:value={value} on:change={() => myfunc()}/>` .
Doesn't work.
I get in the console
`Uncaught ReferenceError: $props is not defined
    at HTMLInputElement.onInput (Input.svelte:119)`
Even if I use instead
`<Input type="text" bind:value={value} on:input={() => myfunc()}/>`  no luck. Same error.

Maybe something inspired from this approach could do the trick?
https://github.com/hperrin/svelte-material-ui/blob/master/packages/textfield/Input.svelte

**Comment by c0bra** [comment]
@mihaimiculescu thanks for reporting. This should be fixed in 0.3.1 which was just released.
