### ISSUE TITLE
cannot import "bulma/css/bulma.css";

### ISSUE THREAD

**Issue by qqke** [c0bra/svelma#5]
Import Bulma's CSS in my main app's component
get the error:

bundles src/main.js → public/bundle.js...
[!] Error: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)
node_modules/bulma/css/bulma.css (2:0)
1: /*! bulma.io v0.7.5 | MIT License | github.com/jgthms/bulma */
2: @-webkit-keyframes spinAround {
   ^
3:   from {
4:     -webkit-transform: rotate(0deg);
Error: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)

**Comment by c0bra** [comment]
@qqke you'll need a rollup plugin that allows you to handle css imports. I should put that in the docs.

I'm using [svelte-preprocess](https://www.npmjs.com/package/svelte-preprocess)

**Comment by hillar** [comment]
mhmh, same happens on svelte.dev/repl

**Comment by hillar** [comment]
however, this seems to work on svelte.dev/repl

```
<script>
	
	import { onMount } from 'svelte';
	import { Field, Input } from 'svelma'
	
	onMount(() => {
		const bulma = document.createElement('link');
		bulma.rel = 'stylesheet';
		bulma.href = 'https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css';
		document.head.appendChild(bulma);
		const fontawesome = document.createElement('link');
		fontawesome.rel = 'stylesheet';
		fontawesome.href = 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css';
		document.head.appendChild(fontawesome);
		return () => {
			bulma.parentNode.removeChild(bulma);
			fontawesome.parentNode.removeChild(fontawesome);
		};
	});

	let bound = {
		name: 'Rich Harris',
		email: 'rich@',
		username: 'richie55',
		password: 'secret123',
	}
	
</script>

<div class="box">
	
	<Field label="Name">
		<Input type="text" bind:value={bound.name} placeholder="Text input" />
	</Field>

	<Field label="Email" type="is-danger" message="Invalid email">
		<Input type="email" bind:value={bound.email} maxlength="30" />
	</Field>

	<Field label="Username" type="is-success" message="Username available">
		<Input type="email" bind:value={bound.username} />
	</Field>

	<Field label="Password">
		<Input type="password" bind:value={bound.password} passwordReveal={true} />
	</Field>

	<Field label="Textarea">
		<Input type="textarea" maxlength="200" />
	</Field>
</div>
```

**Comment by c0bra** [comment]
Yea the repl can't import css files AFAIK. You can fork one of the demos from the docs site in codesandbox.io as a starting point if you want.

Going to close this since it seems fixed.

**Comment by vanslly** [comment]
The docs say to use `rollup-plugin-postcss` but was unable to get it working as postcss seems to be scoping the bulma css import. Using `svelte-preprocess` definitely worked for me and wish the docs suggested that instead.
