### ISSUE TITLE
Wrong guide 

### ISSUE THREAD

**Issue by rodshtein** [c0bra/svelma#66]
I tried to build basic project by guides on github, and still #20

**Comment by c0bra** [comment]
Thanks for reporting, @zamkevich. I will take a look.

**Comment by c0bra** [comment]
@zamkevich I did a test and had to add `svelte-preprocess` to get it to compile.  I've updated the README with that info so if you want to try again you should have better luck.

Let me know how it goes!

**Comment by rodshtein** [comment]
One moment

**Comment by rodshtein** [comment]
@c0bra Still did work.
![image](https://user-images.githubusercontent.com/13717428/91062254-d5be5380-e66f-11ea-935f-43769a88080f.png)

Actually a am here because one guy ask me for help with Svelma.  
And i know what the problem 😏  

For example: what do you expect from this? 

![image](https://user-images.githubusercontent.com/13717428/91062338-eb337d80-e66f-11ea-83af-0371a9965749.png)

Get all styles to Svelte app? Do you know that the Svelte will clean all unused styles. And frome it's point of view all the styles are unused. 

And from this? Import styles to html? But whole config working only with js... 

![image](https://user-images.githubusercontent.com/13717428/91062389-fbe3f380-e66f-11ea-87c6-1ddd104475bf.png)

**Comment by abbychau** [comment]
the rollup config is now rewritten to new rollup version dependencies.
Is this still happening?

**Comment by abbychau** [comment]
feel free to reopen if there is still problem.
