### ISSUE TITLE
Draggable tiles break website.

### ISSUE THREAD

**Issue by lpshanley** [c0bra/svelma#7]
https://c0bra.github.io/svelma/bulma/tiles

Draggabilly is not defined in the component and is breaking the page. :-)

**Comment by c0bra** [comment]
What's your browser/connection speed, etc? I can't reproduce in Firefox or Chrome.

Might be a race condition?

**Comment by lpshanley** [comment]
I was using chrome and I have 450 / 35 with ~15ms latency

**Comment by c0bra** [comment]
@lpshanley Anything weird happening in your network panel? Could an ad blocker be preventing the script from loading?

**Comment by lpshanley** [comment]
That's really odd. Seems to be working at the moment. Next time I am at that machine I will see if I can reproduce again and find a better cause.

**Comment by c0bra** [comment]
I was able to reproduce this. If you start from another page and then navigate to the tiles page it breaks.

**Comment by c0bra** [comment]
Will be fixed in next release.
