### ISSUE TITLE
codesandbox example isnt working

### ISSUE THREAD

**Issue by ghost** [c0bra/svelma#84]
neither firefox nor chrome can complete the loading, for different reasons, but still;
had to set cookies to extra-permissive to even get this far tbh

![svelma-firefox](https://user-images.githubusercontent.com/59403389/104793187-ae446080-57a1-11eb-948b-eea0aa065fdc.png)

![svelma-chrome](https://user-images.githubusercontent.com/59403389/104793194-b1d7e780-57a1-11eb-8d00-5f7a91153556.png)

**Comment by bmaupin** [comment]
I had the same problem!

Here's what I did:

1. Go to any of the component pages (e.g. https://c0bra.github.io/svelma/components/input)
2. Click *Codesandbox*
3. In package.json change
   
   ```json
   "svelte": "latest",
   ```

   to

   ```json
   "svelte": "^3.0.0",
   ```
4. Save package.json (Ctrl+S)
5. In the Browser tab click the reload button (it doesn't seem to automatically reload)
